# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Edvora_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD'
  pod 'SwiftKeychainWrapper'
  pod 'Toast-Swift'
  
end
